version: "3.8"
services:
    nodeserver:
        build:
            context: ./
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
    nginx2:
        restart: always
        build:
            context: ./nginx2
        ports:
            - "8180:80"
